controller_list:
  - name: fake_bb_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_bb_gripper_controller
    joints:
      - joint7
initial:  # Define initial robot poses.
  - group: bb_arm
    pose: home
  - group: bb_gripper
    pose: closed