# gazebo_ros_control_params.yaml
gazebo_ros_control/pid_gains:
  joint1: {p: 2000.0, i: 0.0, d: 1.0}
  joint2: {p: 2000.0, i: 0.0, d: 1.0}
  joint3: {p: 2000.0, i: 0.0, d: 1.0}
  joint4: {p: 2000.0, i: 0.0, d: 1.0}
  joint5: {p: 2000.0, i: 0.0, d: 1.0}
  joint6: {p: 2000.0, i: 0.0, d: 1.0}
  joint7: {p: 1000.0, i: 0.0, d: 1.0}